src/main/webapp/css/navi.css
src/main/webapp/js/navi.js
src/main/webapp/js/util.js
src/main/webapp/scss/navi.scss
src/main/webapp/views/navi.html

@yuu-nkjm
* 通知部分のスタイルを整えました。
* s/formated/formatted
* 時刻を`時:分`だけにしてみました。これで必要十分かと個人的には思うのですがいかがでしょうか？（問題あれば差し戻します）> @reikohishiyama

通知のスタイルの修正

---

src/main/webapp/js/navi.js

[WIP] #19 移動ログの取得

---

src/main/webapp/css/ranking.css
src/main/webapp/jaxrs-view-root/ranking.html
src/main/webapp/js/ranking.js
src/main/webapp/scss/ranking.scss

addRankingに対応

---

src/main/webapp/js/navi.js
src/main/webapp/js/util.js

#26 
@yuu-nkjm  修正しました。こちらでいかがでしょうか。
なお、月日は0padingしています。

#26 アクティビティの日付表示を変更

---

src/main/webapp/css/checkpoints.css
src/main/webapp/js/checkpoints.js
src/main/webapp/scss/_settings.scss
src/main/webapp/scss/checkpoints.scss

チェックポイント一覧でnameを追加

---

src/main/webapp/css/header.css
src/main/webapp/scss/header.scss
src/main/webapp/templates/header.html

ナビゲーションドロップダウンの整理

---

src/main/webapp/js/task-common.js
src/main/webapp/templates/modal.html

タスクに対するレスポンスを追加

---

src/main/webapp/css/visited-checkpoints.css
src/main/webapp/jaxrs-view-root/task-description.html
src/main/webapp/jaxrs-view-root/visited-checkpoints.html
src/main/webapp/js/task-common.js
src/main/webapp/js/util.js
src/main/webapp/js/visited-checkpoints.js
src/main/webapp/scss/visited-checkpoints.scss
src/main/webapp/templates/header.html

訪問済みフラグの表示

---

src/main/webapp/js/navi.js

#52 移動ログに取得日時を追加

---

src/main/webapp/css/visited-checkpoints.css
src/main/webapp/js/checkpoints.js
src/main/webapp/js/task-common.js
src/main/webapp/js/util.js
src/main/webapp/js/visited-checkpoints.js
src/main/webapp/scss/visited-checkpoints.scss

#54 チェックポイント一覧画面の表示項目を変更

---

src/main/webapp/js/navi.js

ナビ画面のマップ表示領域を調整

---

src/main/webapp/css/common.css
src/main/webapp/css/header.css
src/main/webapp/jaxrs-view-root/index.html
src/main/webapp/js/login.js
src/main/webapp/scss/common.scss
src/main/webapp/scss/header.scss
src/main/webapp/templates/header.html

* トップ画面とログイン画面で`メニュー`を表示しないように
* タイトルとメニューが被らないように、タイトルフォントを小さく

ヘッダーのタイトルとメニューの修正

---

src/main/java/org/magcruise/citywalk/ApplicationContext.java
src/main/java/org/magcruise/citywalk/conv/CheckpointsAndTasksFactory.java
src/main/java/org/magcruise/citywalk/conv/InitialDataFactory.java
src/main/java/org/magcruise/citywalk/model/json/db/CheckpointJson.java
src/main/java/org/magcruise/citywalk/model/json/init/CheckpointJson.java
src/main/java/org/magcruise/citywalk/model/relation/CheckpointsTable.java
src/main/java/org/magcruise/citywalk/model/row/Checkpoint.java
src/main/webapp/css/checkpoints.css
src/main/webapp/jaxrs-view-root/checkpoints.html
src/main/webapp/js/checkpoints.js
src/main/webapp/js/util.js
src/main/webapp/json/checkpoints-and-tasks/waseda.json
src/main/webapp/scss/checkpoints.scss
src/test/java/org/magcruise/citywalk/model/TableModelTest.java

チェックポイントのカテゴリ分け

---

src/main/webapp/js/navi.js

自分の位置情報について

---

src/main/webapp/jaxrs-view-root/task-photo.html
src/main/webapp/jaxrs-view-root/task-qr.html

#71 写真を選ぶ際の文言修正

---

src/main/webapp/js/navi.js

#74 ナビ画面で位置情報が更新されない

---

src/main/webapp/js/checkpoints.js
src/main/webapp/js/navi.js
src/main/webapp/js/util.js

#51 チェックポイント一覧画面で現在地を表示

---

src/main/webapp/js/checkpoints.js

#77 チェックポイント一覧画面で現在地を含めて地図を表示する

---

src/main/webapp/css/register.css
src/main/webapp/jaxrs-view-root/index.html
src/main/webapp/jaxrs-view-root/login.html
src/main/webapp/jaxrs-view-root/register.html
src/main/webapp/js/login.js
src/main/webapp/js/register.js
src/main/webapp/js/util.js
src/main/webapp/scss/register.scss
src/main/webapp/templates/header.html

ユーザー登録機能の追加

---

src/main/webapp/js/register.js

@yuu-nkjm 確認後、問題がなければマージお願いします。

register.js内のRPCの戻り値をチェック

---

src/main/webapp/css/ranking.css
src/main/webapp/jaxrs-view-root/ranking.html
src/main/webapp/js/ranking.js
src/main/webapp/scss/ranking.scss

#91 ランキング画面でのスコアの表示

---

src/main/webapp/css/header.css
src/main/webapp/fragment/header.html
src/main/webapp/js/util.js
src/main/webapp/scss/header.scss

#86 メニューの１行目にログインユーザ名を表示

---

src/main/webapp/js/visited-checkpoints.js

#80 訪問済みチェックポイント一覧画面にて詳細分を表示

---

src/main/webapp/js/ranking.js

safariにおけるランキング表示の修正

---

src/main/webapp/jaxrs-view-root/checkpoints.html
src/main/webapp/jaxrs-view-root/navi.html
src/main/webapp/js/checkpoints.js
src/main/webapp/js/navi.js

#108 マップ読み込みタイミングの変更

---

src/main/java/org/magcruise/citywalk/jaxrs/CityWalkView.java
src/main/webapp/jaxrs-view-root/clear.html
src/main/webapp/jaxrs-view-root/index.html

#118 clear.htmlにアクセス時にローカルストレージをクリア。

#118 clear.htmlでローカルストレージをクリア

---

src/main/java/org/magcruise/citywalk/ApplicationContext.java
src/main/java/org/magcruise/citywalk/conv/CheckpointsAndTasksFactory.java
src/main/java/org/magcruise/citywalk/conv/InitialDataFactory.java
src/main/java/org/magcruise/citywalk/model/json/db/CheckpointJson.java
src/main/java/org/magcruise/citywalk/model/json/init/CheckpointJson.java
src/main/java/org/magcruise/citywalk/model/relation/CheckpointsTable.java
src/main/java/org/magcruise/citywalk/model/row/Checkpoint.java
src/main/webapp/json/checkpoints-and-tasks/waseda.json
src/test/java/org/magcruise/citywalk/model/TableModelTest.java

descriptionを表示できる． 機能追加だけなので衝突はないはず．
#80

#80 description の追加

---

src/main/java/org/magcruise/citywalk/model/json/init/TaskJson.java
src/main/java/org/magcruise/citywalk/model/row/Activity.java
src/main/java/org/magcruise/citywalk/model/task/PinTask.java
src/main/webapp/jaxrs-view-root/task-pin.html
src/main/webapp/js/task-common.js
src/main/webapp/js/task-pin.js
src/main/webapp/json/checkpoints-and-tasks/waseda.json

@ayakix 
task-description.js を微修正して， task-pin.js を作った．
差分だけ実装したかったけど，僕のJS力だと難しい．
機能追加だけなので，衝突はないはず．
#101

4桁数字のタスク(PinTask) を追加した． #101

---

src/main/webapp/js/navi.js

#108 watchPositionのmaximumAgeを0に

---

src/main/java/org/magcruise/citywalk/jaxrs/CityWalkView.java
src/main/webapp/js/login.js

@ayakix 
セッションがクリアされた状態でログインが必要なページにアクセスした場合，「ログアウトされました．再ログインして下さい．」と表示して，login.htmlに飛ばす．
元のアクセスページをパラメータ渡しし，ログイン後にそこにリダイレクトするようにした．
@reikohishiyama の手元で動作を確認．
#132

#132 ブラウザのセッションがクリアされた場合の対応

---

src/main/webapp/css/task-qr.css
src/main/webapp/scss/task-qr.scss

fix: QRコードタスク画面でF5を押すとnopicture.svgが消える

---

src/main/webapp/css/checkpoints.css
src/main/webapp/js/checkpoints.js
src/main/webapp/scss/checkpoints.scss

リロードせずにチェックポイントの絞込 #135

---

src/main/java/org/magcruise/citywalk/ApplicationContext.java
src/main/java/org/magcruise/citywalk/conv/CheckpointsAndTasksFactory.java
src/main/java/org/magcruise/citywalk/conv/InitialDataFactory.java
src/main/java/org/magcruise/citywalk/model/gdata/GoogleSpreadsheetData.java
src/main/java/org/magcruise/citywalk/model/json/db/CheckpointJson.java
src/main/java/org/magcruise/citywalk/model/json/init/CheckpointJson.java
src/main/java/org/magcruise/citywalk/model/relation/CheckpointsTable.java
src/main/java/org/magcruise/citywalk/model/row/Checkpoint.java
src/main/webapp/js/checkpoints.js
src/main/webapp/js/navi.js
src/main/webapp/json/checkpoints-and-tasks/waseda.json
src/main/webapp/json/checkpoints-and-tasks/wasedasai2016.json
src/test/java/org/magcruise/citywalk/model/TableModelTest.java

チェックポイントの吹き出しに表示する情報

---

src/main/webapp/css/common.css
src/main/webapp/scss/common.scss

リンクhover時に半透明にするスタイルを削除

---

src/main/java/org/magcruise/citywalk/jsonrpc/CityWalkService.java
src/main/java/org/magcruise/citywalk/jsonrpc/CityWalkServiceClient.java
src/main/java/org/magcruise/citywalk/jsonrpc/CityWalkServiceInterface.java
src/main/java/org/magcruise/citywalk/model/json/RegisterResultJson.java
src/main/webapp/js/signup.js
src/main/webapp/scss/top.scss

#184 ニックネームの最大文字数以内でニックネームを推薦するようにした

#184 ニックネームの最大文字数以内でニックネームを推薦するようにした

---

src/main/java/org/magcruise/citywalk/jsonrpc/CityWalkService.java
src/main/java/org/magcruise/citywalk/model/relation/VerifiedActivitiesTable.java
src/main/webapp/js/score.js

- サーバ側ではX位以下を取得できるようにした
- クライアント側では最大の列数で制限できるようにした

#192  ランキング表示の上限の設定
